### ISSUE TITLE
best_result of grid search has no attribute hyper_Galax_image_path_dict

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#129]
Traceback (most recent call last):
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/autolens_workspace_jam/cosma/subhalo_jam/runners/big_hst_psf_mask/inversion_hyper.py", line 179, in <module>
    pipeline.run(dataset=imaging, mask=mask, positions=positions)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/pipeline.py", line 15, in run
    return self.run_function(runner, data_name)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autofit/tools/pipeline.py", line 186, in run_function
    results.add(name, func(phase, results))
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/pipeline.py", line 12, in runner
    dataset=dataset, results=results, mask=mask, positions=positions
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/dataset/phase.py", line 72, in run
    dataset=dataset, mask=mask, results=results, positions=positions
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/imaging/phase.py", line 143, in make_analysis
    results=results,
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/imaging/analysis.py", line 11, in __init__
    super(Analysis, self).__init__(cosmology=cosmology, results=results)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/dataset/analysis.py", line 15, in __init__
    last_results.hyper_galaxy_image_path_dict
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/grid_search.py", line 39, in __getattr__
    return getattr(self.best_result, item)
AttributeError: 'Result' object has no attribute 'hyper_galaxy_image_path_dict'

Need to think about this one - suggests that a best_result doeosnt quite have accessible the attributes of a normal phase.

**Comment by Jammy2211** [comment]
I have fixed this with a dodgy if loop for now.

This has actually made me realise a more important issue - we only want to pass hyper image between phases if a hyper-phase extension is performed. Currently, we do this 100% of the time between phases in all pipelines, but soon we will want the option of not.

So, that is actually the new functionality we need and will address this issue.
