### ISSUE TITLE
Autoconf conf.py - Key error

### ISSUE THREAD

**Issue by allangabrielsch** [Jammy2211/PyAutoLens#214]
Hello! 

While running the scripts for the Howtolens lectures, specifically Ch.2, Tut. 1 - Non-linear search, I'm obtaining the following error:

```
2023-03-20 18:42:16,087 - autofit.non_linear.abstract_search - INFO - Creating search
Dynesty has begun running - checkout the autolens_workspace/output/ folder for live output of the results, images and lens model. 
2023-03-20 18:42:16,088 - tutorial_1_non_linear_search - INFO - Starting search
2023-03-20 18:42:16,781 - autogalaxy.analysis.analysis - INFO - PRELOADS - Setting up preloads, may take a few minutes for fits using an inversion.
2023-03-20 18:42:16,974 - tutorial_1_non_linear_search - INFO - Saving path info
2023-03-20 18:42:17,008 - tutorial_1_non_linear_search - INFO - Not complete. Starting non-linear search.
2023-03-20 18:42:17,008 - tutorial_1_non_linear_search - INFO - No Dynesty samples found, beginning new non-linear search. 
Traceback (most recent call last):
  File "/home/allan/.local/lib/python3.8/site-packages/autoconf/conf.py", line 61, in __getitem__
    return self._dict[key]
KeyError: 'force_x1_cpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/allan/Desktop/autolens_workspace/scripts/howtolens/chapter_2_lens_modeling/tutorial_1_non_linear_search.py", line 272, in <module>
    result = search.fit(model=model, analysis=analysis)
  File "/home/allan/.local/lib/python3.8/site-packages/autofit/non_linear/abstract_search.py", line 523, in fit
    self._fit(
  File "/home/allan/.local/lib/python3.8/site-packages/autofit/non_linear/nest/dynesty/abstract.py", line 161, in _fit
    if conf.instance["non_linear"]["nest"][self.__class__.__name__][
  File "/home/allan/.local/lib/python3.8/site-packages/autoconf/conf.py", line 63, in __getitem__
    raise KeyError(f"key {key} not found in paths {self.paths_string}")
KeyError: 'key force_x1_cpu not found in paths /home/allan/config\n/home/allan/.local/lib/python3.8/site-packages/autolens/config\n/home/allan/.local/lib/python3.8/site-packages/autogalaxy/config\n/home/allan/.local/lib/python3.8/site-packages/autofit/config\n/home/allan/.local/lib/python3.8/site-packages/autoarray/config'
```

and also when running Ch1 Tutorial 3:

  ```
intensity of `Grid2D` pixel 2:
0.04838914231548955
etc.
Traceback (most recent call last):
  File "/home/allan/.local/lib/python3.8/site-packages/autoconf/conf.py", line 61, in __getitem__
    return self._dict[key]
KeyError: 'grid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/allan/Desktop/autolens_workspace/scripts/howtolens/chapter_1_introduction/tutorial_3_galaxies.py", line 65, in <module>
    galaxy_image_1d = galaxy_with_light_profile.image_1d_from(grid=grid_2d)
  File "/home/allan/.local/lib/python3.8/site-packages/autoarray/structures/structure_decorators.py", line 150, in wrapper
    result = func(obj, grid, *args, **kwargs)
  File "/home/allan/.local/lib/python3.8/site-packages/autogalaxy/galaxy/galaxy.py", line 277, in image_1d_from
    grid_radial = self.grid_radial_from(
  File "/home/allan/.local/lib/python3.8/site-packages/autogalaxy/galaxy/galaxy.py", line 177, in grid_radial_from
    return grid.grid_2d_radial_projected_from(
  File "/home/allan/.local/lib/python3.8/site-packages/autoarray/structures/grids/uniform_2d.py", line 1100, in grid_2d_radial_projected_from
    if conf.instance["general"]["grid"]["remove_projected_centre"]:
  File "/home/allan/.local/lib/python3.8/site-packages/autoconf/conf.py", line 63, in __getitem__
    raise KeyError(f"key {key} not found in paths {self.paths_string}")
KeyError: 'key grid not found in paths /home/allan/config\n/home/allan/.local/lib/python3.8/site-packages/autolens/config\n/home/allan/.local/lib/python3.8/site-packages/autogalaxy/config\n/home/allan/.local/lib/python3.8/site-packages/autofit/config\n/home/allan/.local/lib/python3.8/site-packages/autoarray/config'
```

I installed Autolens with pip and if it matters the version of autoconf is 2023.1.15.1. 
Running Zorin OS16.2 and Python 3.8.10
(All seems to work when running it from the Jupyter Notebook though)

Thanks in Advance :)

**Comment by Jammy2211** [comment]
First, can you check if your following config file at `/home/allan/config`:

https://github.com/Jammy2211/autolens_workspace/blob/release/config/non_linear/nest.yaml

Has the input 

```
DynestyStatic:
  parallel:
    number_of_cores: 1              # The number of cores the search is parallelized over by default, using Python multiprocessing.
    force_x1_cpu: false             # Force Dynesty to not use Python multiprocessing Pool, which can fix issues on certain operating systems.
```

If `force_x1_cpu` is not there, add it and you should be sorted.

It could be a bug (which we've fixed but not had a chance to release yet) causing the issue. If this is the case, you can fix this by adding the following to the `DynestyStatic` objects when you use them:

```
search = af.DynestyStatic(
    path_prefix=path.join("howtolens", "chapter_2"),
    name="tutorial_1_non_linear_search",
    unique_tag=dataset_name,
    nlive=40,
    walks=5,
    force_x1_cpu=False
)
```

Let me know if it still doesn't work!

**Comment by allangabrielsch** [comment]
Thanks,

I tried both but nothing yet. 
I checked the nest.yaml fine in `.local/lib/python3.8/site-packages/autofit/config` and the one in the workspace, they both have `force_x1_cpu=False`
Also tried running it with the modified `DynestyStatic` object and still raising the same exception. 
Let me know whatever else you might need.

**Comment by Jammy2211** [comment]
I have done a new release, which will hopefully fix the issue.

To fix this, try installing the nmew autolens via `pip install autolens==2023.3.21.5`

You may also need to download the new https://github.com/Jammy2211/autolens_workspace

**Comment by Jammy2211** [comment]
:)
