### ISSUE TITLE
Note on implementing hyper functionality

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#98]
This issue is notes on my time implementing hyper functionality, as I will likely forget these things others.

- The inversion module is a mess, especially where we combine mappers with regularization with an inversion. This needs a significant refactor, albeit I would recommend we do this after the multi-plane ray tracing refactor.

- As a result of this mess, the unit tests for the AdaptiveRegulrization scheme are missing. I could easily have done this on lens_fit, but I cannot find a Weighted Regularization matrix that does not raise an error for an invalid Cholesky decomposition. Nevertheless, I have confirmed it is working using integration tests, and an image confirming it is behaving as expected is also output.

- We need to make some choices for how a Adaptive Regularization scheme works. The hyper image used to weight the source pixels cannot contain negative values. Thus, I currently increase all vales below 1% the max to 1% of the max. It may be better to introduce another hyper parameter controlling this.

**Comment by Jammy2211** [comment]
We have a function that checks if any pixels in a hyper image being passed were masked in a previous phase. It does this by looking for zeros.

This runs between every phase, regardless of whether hyper functionality is being used. We need to disable image passing if no model components that use hyper functionality are being used (this will save memory as well).

**Comment by Jammy2211** [comment]
At the end of a phase without hyper images, there is no hyper_model_image or hyper_galxy_image_dict in the Anaylsis class. This is the expected behaviour, however, following a HyperGalaxyPhase, we attach hyper_galaxies to the results of that phase (e.g. self.constant). This means that, in the next phase, when the Results class is used to generate the hyper images, errors are raised because this hyper_galaxy is used to scale the noise (raising an error, as it has no associated hyper images).

For now, my solution is to manually attach these images to the analysis instance of the results, in the HyperGalaxyPhase. This is fine however, **If there is an inversion used, this scaling of the noise-map will change the hyper galaxy image at the start of the next phase**.

The best solution is probably to avoid putting the hyper_galaxy in the results.constant, but somewhere else, as this is essentially 'changing' the result of a phase.

**Comment by Jammy2211** [comment]
The uses_hyper_images property, which determines if hyper images are setup in a phase, does not switch to True if a hyper_galaxy is passed via pass_priors. This means images are not set up correctnyl unless the hyper_galaxy(s) are explicitly passed into the galaxies input of a Phase in a pipeline.

**Comment by Jammy2211** [comment]
The PixelizationPhase works as expected. We should update the API to change where results are stored, as discussed in the issue I just opened.

To get it to work, I had to make its Analysis class inherit from LensSourcePlanePhase, so it had the correct methods for setting up a tracer. I dont view this is a long term issue (i.e. if MultiPlane is used), as we will reduce all Phases to one class soon now that we are moving to a generic tracer.

**Comment by Jammy2211** [comment]
**Current issues with hyper API**

- The last.results.hyper attribute is not a result, but a ResultsCollection. 

- The last.result does not refer to the last result of a normal phase. This may be due to the bug above, but is worth noting as a desired behaviour.

- After a HyperPhase, we cannot pass priors using a result without a .hyper, e.g.:

```
    class HyperLensPlanePhase(phase_imaging.LensPlanePhase):

        def pass_priors(self, results):

            self.lens_galaxies.lens.hyper_galaxy = results.from_phase('phase_1').hyper.\
                constant.lens_galaxies.lens.hyper_galaxy

            self.lens_galaxies.lens.light = results.from_phase('phase_1').\
                variable.lens_galaxies.lens.light
```

The above raises an error when passing lens.light.

**Whats needed from the API**

- If we call results.last, it should always go to the last results of a REGULAR (e.g. non Hyper) phase. Alll hyper results should be stored in a results.hyper attribute. This is key to ensuring image passing works correctly.

- We want a HyperPhase to take a Phase in a pipeline, with bools customizing what hyper functionality it optimizes e.g.:

`phase1h = HyperPhase(phase=phase1, hyper_noise_scaling=True, hyper_pixelization_regularization=False, hyper_magic=False)
`
This phase will end with a HyperAllPhase, which optimizes all of the True components simultaneously (after fitting each in its own non-linear search individually).

- The command above should not input a phase_name. If we need a phase_name for parts of the code, simply append it with default strings. For example:
```
phase_1 = phase_imaging.LensSourcePlanePhase(phase_name='phase_1')
phase_1h = HyperPhase(phase=phase1, hyper_noise_scaling=True, hyper_pixelization_regularization=True)
```

The phase names of the phase_1h can append to the string as follows:

```
'phase_1_hyper_noise_scaling_lens'
'phase_1_hyper_noise_scaling_source'
'phase_1_hyper_pixelization_regularization'
'phase_1_hyper_all'
```

- When passing priors, we should be able to use the .hyper results mixed in with the normal results, of a given phase, using that phase's name, for example:

```
    class HyperLensPlanePhase(phase_imaging.LensPlanePhase):

        def pass_priors(self, results):

            self.lens_galaxies.lens.hyper_galaxy = results.from_phase('phase_1').hyper.\
                constant.lens_galaxies.lens.hyper_galaxy

            self.lens_galaxies.lens.light = results.from_phase('phase_1').\
                variable.lens_galaxies.lens.light
```

Where .hyper corresponds to the HyperAllPhase.

- When running a pipeline, we ideally own't need to pass each hyper phase, e.g. phase1h. So, this:
`
    return pl.PipelineImaging(pipeline_name, phase1,phase2)`

Instead of this:

`    return pl.PipelineImaging(pipeline_name, phase1, phase1h, phase2)`

To do this, can we extend phases rather then create new instances, so something like:

```
phase_1 = phase_imaging.LensSourcePlanePhase(phase_name='phase_1')
phase_1.perform_hyper_phase(hyper_noise_scaling=True, hyper_pixelization_regularization=True)
```

**Comment by Jammy2211** [comment]
**Multiple Hyper Phases**

If we run multiple hyper phases, the question arises, where does the HyperPhase get it parameter priors from? The options are:

- It uses default priors from the configs, ignoring all previous hyper phases.

- It uses GaussianPriors based on the results of the previous HyperPhase. If a component was not in the previous hyper phase (e.g. hyper_noise_scaling=False), then it should automatically use defaults. 

If its easier, for now just implement option 1, but we'll want option 2 in the end.

**Comment by Jammy2211** [comment]
I've had to build hacks around two issues that cropped up:

1) The CombinedHyperPhase did not use phase_imaging to setup the phase passed into it. This means that for a PixelizationPhase the phase settings (e.g. the sub_grid_size) were not passed, which mean the path used for the analsys was incorrect. I have hacked this to use a PhaseImagnig, but am aware you'll want to do something more clever as this removes the generalizing of the CombinedHyperPhase.

2) The path of an optimizer (which uses the sym link) does not update as a property. This meant that the path used to output optimizer results for a new hyper phase was not updated. To overcome this in the HyperPhase class's make_hyper_phase method I overwrite the optmizer with a new MultiNest instance, using the phase's correct information to setup the paths correctly.

**Comment by Jammy2211** [comment]
I've uncommented three test in phase_extensions (HyperPhaseAPI) due to these hacks.

**Comment by Jammy2211** [comment]
The main issue remaining is that if an inversion in a previous phase is set to constant (in the main phase, not an extension phase), the inversion in the following inversion phase of the extension does not get set variable parameters :(.

**Comment by Jammy2211** [comment]
I think commands which link parameters are also calling a bug. an example is a command linking two centres:
```

                self.lens_galaxies.lens.bulge.centre = (
                    self.lens_galaxies.lens.disk.centre
                )
```

This produces the following error:
```

Traceback (most recent call last):
  File "/home/jammy/PycharmProjects/PyAutoLens/workspace_jam/runners/slacs/slacs.py", line 144, in <module>
    pipeline.run(data=ccd_data, mask=mask, positions=positions)
  File "/home/jammy/PycharmProjects/PyAutoLens/autolens/pipeline/pipeline.py", line 9, in run
    return self.run_function(runner, data_name)
  File "/home/jammy/PycharmProjects/VirtualEnvs/PyAutoLens/lib/python3.6/site-packages/autofit/tools/pipeline.py", line 167, in run_function
    results.add(name, func(phase, results))
  File "/home/jammy/PycharmProjects/PyAutoLens/autolens/pipeline/pipeline.py", line 7, in runner
    return phase.run(data=data, results=results, mask=mask, positions=positions)
  File "/home/jammy/PycharmProjects/PyAutoLens/autolens/pipeline/phase/phase_imaging.py", line 169, in run
    result = self.run_analysis(analysis)
  File "/home/jammy/PycharmProjects/VirtualEnvs/PyAutoLens/lib/python3.6/site-packages/autofit/tools/phase.py", line 81, in run_analysis
    return self.optimizer.fit(analysis)
  File "/home/jammy/PycharmProjects/VirtualEnvs/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/non_linear/non_linear.py", line 521, in timed_function
    result = func(optimizer_instance, *args, **kwargs)
  File "/home/jammy/PycharmProjects/VirtualEnvs/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/non_linear/multi_nest.py", line 195, in fit
    self.output_results(during_analysis=False)
  File "/home/jammy/PycharmProjects/VirtualEnvs/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/non_linear/multi_nest.py", line 381, in output_results
    formatter.add((prior_path, self.format_str.format(most_likely[i])))
IndexError: list index out of range
```

It would appear that it is over-count priors when parameters are linked, as this error suggests it is loading results from the most likely lens model. It would appear it thinks the most likely lens model has more parameters than it actually does.

**Comment by Jammy2211** [comment]
Masks and positions were lost in the pipeline.run functions, meaning default masks were used in hyepr phases and posoitionos omitted complletely. I have added positions  and masks to run functions such that they are used correclty in hyper phases.

**Comment by Jammy2211** [comment]
Masks now cannot change in a hyper pipeline and the masks are fed through the pipeline using the results, rather than masks themselves.

The following bug occurs in the hyper_combined phase, specifically phase 1 o the inversion pipeline. It would appear that for some reason, the hyper_galaxy's are not being initiated in this phase (noting that previous hyper_galaxy / hyper_combined phases work fine).

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/pymultinest/run.py", line 207, in loglike
    return LogLikelihood(cube, ndim, nparams, lnew)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/non_linear/multi_nest.py", line 128, in __call__
    likelihood = self.fit_instance(instance)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autofit/optimize/non_linear/non_linear.py", line 258, in fit_instance
    likelihood = self.analysis.fit(instance)
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/phase_imaging.py", line 534, in fit
    hyper_noise_background=hyper_noise_background,
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/pipeline/phase/phase_imaging.py", line 694, in fit_for_tracer
    hyper_noise_background=hyper_noise_background,
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/lens_fit.py", line 103, in for_data_and_tracer
    hyper_noise_background=hyper_noise_background,
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/lens_fit.py", line 410, in __init__
    noise_map_1d=lens_data.noise_map_1d
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/ray_tracing.py", line 512, in hyper_noise_map_1d_from_noise_map_1d
    noise_map_1d=noise_map_1d
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/ray_tracing.py", line 524, in hyper_noise_maps_1d_of_planes_from_noise_map_1d
    for plane in self.planes
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/ray_tracing.py", line 524, in <listcomp>
    for plane in self.planes
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/plane.py", line 746, in hyper_noise_map_1d_from_noise_map_1d
    noise_map_1d=noise_map_1d
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autolens/lens/plane.py", line 769, in hyper_noise_maps_1d_of_galaxies_from_noise_map_1d
    hyper_noise_map_1d = galaxy.hyper_galaxy.hyper_noise_map_from_hyper_images_and_noise_map(
  File "/cosma/home/dp004/dc-nigh1/PyAutoLens/lib/python3.6/site-packages/autofit/mapper/prior_model/prior_model.py", line 229, in __getattr__
    self.__getattribute__(item)
AttributeError: 'PriorModel' object has no attribute 'hyper_noise_map_from_hyper_images_and_noise_map'

**Comment by Jammy2211** [comment]
Notes to self:

-Begin testing hyper pipelines using LSST quality simulated data for speed.

- Make it so all extended phases do not use previous priors or constants of a hyper galaxy / inversion phase.

- Combine hyper galaxy phase int one NLO. This will require hyper galaxy dict to be used for all images in Analysis.

**Comment by Jammy2211** [comment]
The hyper_galaxy bug, which gives:

AttributeError: 'PriorModel' object has no attribute 'hyper_noise_map_from_hyper_images_and_noise_map'

Is definitely also related to the fact that when an object is a constant, it is not being passed correctly in hyper-phases. However, where the issue was previous in the inversion phase, for hyper galaxies it is, unsurprisingly, in the hyper phase.

Hopefully we have one big mega fix coming :).

**Comment by Jammy2211** [comment]
We need to think carefully about how features which modify the lens data in a phase (modify image, bin_up_factor, signal_to_noise_limit) are incorporated into the hyper_phases. This should just be a matter of rerunning these functions using the copied attributes.

**Comment by Jammy2211** [comment]
Well, I'm glad we got through all of this heartache and that hyper mode now works.
